language: node_js
node_js: "8"
services: postgresql
before_script:
  - psql -c 'create database palettepicker_test;' -U postgres
test:
  adapter: postgresql
  database: palettepicker_test
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
